name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          chmod +x ./node_modules/.bin/cypress  # Add this line to ensure Cypress is executable


      - name: Run Cypress tests (qa - chrome)
        run: npm run cypress:run:qa:chrome
