name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          chmod +x ./node_modules/.bin/cypress 

      - name: Install Cypress binary
        run: npx cypress install  # Ensures Cypress binary is installed



      - name: Run Cypress tests (stag - chrome)
        run: npm run cypress:run:stag:chrome
