name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          chmod +x ./node_modules/.bin/cypress 

      - name: Install Cypress binary
        run: npx cypress install  

      - name: Run Cypress tests (stag - chrome)
        run: npm run cypress:run:stag:chrome

        # Save the screenshots in case tests are failed
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports
          path: cypress/reports